name: Enhancement request
description: Enhance an existing feature in UltimateMenu.
title: "[Enhancement]: "
labels: enhancement
type: enhancement
body:
- type: textarea
  attributes:
    label: Which feature
    description: "Explain which feature you want to see enhanced/improved and what you'd like to be changed about it."
    placeholder: "ex: I'd like to enhance/improve .... because .... ."
  validations:
    required: false
- type: textarea
  attributes:
    label: Reason
    description: Provide Reasoning
    placeholder: "Tell us why you'd want for us to improve this feature in UltimateMenu."
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the request here.
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
